### ISSUE TITLE
[BUG] Respond to the ICA1 feedback

### ISSUE THREAD

**Issue by dhk465** [dhk465/symbolic_comp_one#29]
**Describe the bug**
There are a few problems mentioned in the ICA1 feedback.
They should be resolved before submitting the chatbot with image recognition.

**Code**
* [ ] Diversify the responses of the chatbot

**Style**
* [x] Keep 80 characters per line
* [x] Follow the naming conventions
    * [x] rename helper functions / boolean functions (Issue #28)
    * [x] replace czech words in variables with english (Issue #36 )

**Documentation**
* [x] Separate the github.io page from the README (Issue #39 )
* [ ] Elaborate more on team's design decisions
* [x] Update the README with the latest code (also with ICA2)

**Teamwork**
* [ ] Use issues, code review and pull requests to assist the teamwork
* [ ] Keep the commit messages concise

**Comment by svarnypetr** [comment]
I would suggest listing them as tickboxes or separate issues.

**Comment by dhk465** [comment]
@Slemanof pick some of these to fix
and make a separate issue on each
details should be in our ICA1 feedback
